[build]
builder = "nixpacks"
buildCommand = "cd relay-server && npm install"

[deploy]
startCommand = "node --experimental-modules server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"
workingDirectory = "relay-server"

[deploy.env]
NODE_ENV = "production"
PORT = "3000"
NODE_OPTIONS = "--experimental-modules" 