[build]
builder = "nixpacks"
buildCommand = "cd relay-server && npm install && npm run build"

[deploy]
startCommand = "cd relay-server && node --experimental-modules server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

[deploy.env]
NODE_ENV = "production"
PORT = "3000"
NODE_OPTIONS = "--experimental-modules" 