[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps"

[deploy]
startCommand = "node relay-server/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[deploy.env]
NODE_ENV = "production"
PORT = "3000"
NODE_OPTIONS = "--experimental-modules" 