[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node relay-server/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

[deploy.env]
NODE_ENV = "production"
PORT = "3000" 